---
driver:
  name: docker

test_base_path: spec/integration

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[ntpdate::default]
    attributes:
